(function(b){b.fn.lightbox=function(h){function d(){b("#overlay, #lightbox").remove();a.inprogress=false;if(a.jsonData&&a.jsonData.length>0){var e=a.jsonDataParser?a.jsonDataParser:b.fn.lightbox.parseJsonData;a.imageArray=[];a.imageArray=e(a.jsonData)}var e='<div id="outerImageContainer"><div id="imageContainer"><iframe id="lightboxIframe"></iframe><img id="lightboxImage" /><div id="hoverNav"><a href="javascript://" title="'+a.strings.prevLinkTitle+'" id="prevLink"></a><a href="javascript://" id="nextLink" title="'+
a.strings.nextLinkTitle+'"></a></div><div id="loading"><a href="javascript://" id="loadingLink"><img src="'+a.fileLoadingImage+'"></a></div></div></div>',c='<div id="imageDataContainer" class="clearfix"><div id="imageData"><div id="imageDetails"><span id="caption"></span><span id="numberDisplay"></span></div><div id="bottomNav">';a.displayHelp&&(c+='<span id="helpDisplay">'+a.strings.help+"</span>");c+='<a href="javascript://" id="bottomNavClose" title="'+a.strings.closeTitle+'"><img src="'+a.fileBottomNavCloseImage+
'"></a></div></div></div>';a.navbarOnTop?(b("body").append('<div id="overlay"></div><div id="lightbox">'+c+e+"</div>"),b("#imageDataContainer").addClass("ontop")):b("body").append('<div id="overlay"></div><div id="lightbox">'+e+c+"</div>");b("#overlay, #lightbox").click(function(){m()}).hide();b("#loadingLink, #bottomNavClose").click(function(){m();return false});b("#outerImageContainer").width(a.widthCurrent).height(a.heightCurrent);b("#imageDataContainer").width(a.widthCurrent);a.imageClickClose||
(b("#lightboxImage").click(function(){return false}),b("#hoverNav").click(function(){return false}));return true}function k(){var a,b;if(self.pageYOffset)b=self.pageYOffset,a=self.pageXOffset;else if(document.documentElement&&document.documentElement.scrollTop)b=document.documentElement.scrollTop,a=document.documentElement.scrollLeft;else if(document.body)b=document.body.scrollTop,a=document.body.scrollLeft;return[a,b]}function o(e){b("select, embed, object").hide();n();b("#overlay").hide().css({opacity:a.overlayOpacity}).fadeIn();
imageNum=0;if(!a.jsonData)a.imageArray=[],(!e.rel||e.rel=="")&&!a.allSet?a.imageArray.push([e.href,a.displayTitle?e.title:""]):b("a").each(function(){this.href&&this.rel==e.rel&&a.imageArray.push([this.href,a.displayTitle?this.title:""])});if(a.imageArray.length>1){for(i=0;i<a.imageArray.length;i++)for(j=a.imageArray.length-1;j>i;j--)a.imageArray[i][0]==a.imageArray[j][0]&&a.imageArray.splice(j,1);for(;a.imageArray[imageNum][0]!=e.href;)imageNum++}var c=k(),f=c[1]+b(window).height()/10,c=c[0];b("#lightbox").css({top:f+
"px",left:c+"px"}).show();a.slideNavBar||b("#imageData").hide();g(imageNum)}function g(e){if(a.inprogress==false)a.inprogress=true,a.activeImage=e,b("#loading").show(),b("#lightboxImage, #hoverNav, #prevLink, #nextLink").hide(),a.slideNavBar&&(b("#imageDataContainer").hide(),b("#imageData").hide()),p()}function p(){imgPreloader=new Image;imgPreloader.onload=function(){var e=imgPreloader.width,c=imgPreloader.height;a.scaleImages&&(e=parseInt(a.xScale*e),c=parseInt(a.yScale*c));if(a.fitToScreen){var f=
[b(document).width(),b(document).height(),b(window).width(),b(window).height()],d=f[2]-2*a.borderSize,f=f[3]-200,g=d/f,h=imgPreloader.width/imgPreloader.height;if(imgPreloader.height>f||imgPreloader.width>d)g>h?(e=parseInt(f/imgPreloader.height*imgPreloader.width),c=f):(c=parseInt(d/imgPreloader.width*imgPreloader.height),e=d)}b("#lightboxImage").attr("src",a.imageArray[a.activeImage][0]).width(e).height(c);q(e,c)};imgPreloader.src=a.imageArray[a.activeImage][0]}function m(){l();b("#lightbox").hide();
b("#overlay").fadeOut();b("select, object, embed").show()}function q(e,c){a.widthCurrent=b("#outerImageContainer").outerWidth();a.heightCurrent=b("#outerImageContainer").outerHeight();var f=Math.max(350,e+a.borderSize*2),d=c+a.borderSize*2;wDiff=a.widthCurrent-f;hDiff=a.heightCurrent-d;b("#imageDataContainer").animate({width:f},a.resizeSpeed,"linear");b("#outerImageContainer").animate({width:f},a.resizeSpeed,"linear",function(){b("#outerImageContainer").animate({height:d},a.resizeSpeed,"linear",function(){b("#loading").hide();
b("#lightboxImage").fadeIn("fast");b("#numberDisplay").html("");a.imageArray[a.activeImage][1]&&b("#caption").html(a.imageArray[a.activeImage][1]).show();if(a.imageArray.length>1){var c;c=a.strings.image+(a.activeImage+1)+a.strings.of+a.imageArray.length;a.displayDownloadLink&&(c+="<a href='"+a.imageArray[a.activeImage][0]+"'>"+a.strings.download+"</a>");if(!a.disableNavbarLinks){if(a.activeImage>0||a.loopImages)c='<a title="'+a.strings.prevLinkTitle+'" href="#" id="prevLinkText">'+a.strings.prevLinkText+
"</a>"+c;if(a.activeImage+1<a.imageArray.length||a.loopImages)c+='<a title="'+a.strings.nextLinkTitle+'" href="#" id="nextLinkText">'+a.strings.nextLinkText+"</a>"}b("#numberDisplay").html(c).show()}a.slideNavBar?b("#imageData").slideDown(a.navBarSlideSpeed):b("#imageData").show();n();r();if(a.loopImages&&a.imageArray.length>1)preloadNextImage=new Image,preloadNextImage.src=a.imageArray[a.activeImage==a.imageArray.length-1?0:a.activeImage+1][0],preloadPrevImage=new Image,preloadPrevImage.src=a.imageArray[a.activeImage==
0?a.imageArray.length-1:a.activeImage-1][0];else{if(a.imageArray.length-1>a.activeImage)preloadNextImage=new Image,preloadNextImage.src=a.imageArray[a.activeImage+1][0];if(a.activeImage>0)preloadPrevImage=new Image,preloadPrevImage.src=a.imageArray[a.activeImage-1][0]}a.inprogress=false})});afterTimeout=function(){b("#prevLink").height(c);b("#nextLink").height(c)};hDiff==0&&wDiff==0?jQuery.browser.msie?setTimeout(afterTimeout,250):setTimeout(afterTimeout,100):afterTimeout()}function n(){b("#overlay").css({width:b(document).width(),
height:b(document).height()})}function r(){a.imageArray.length>1&&(b("#hoverNav").show(),a.loopImages?(b("#prevLink,#prevLinkText").show().click(function(){g(a.activeImage==0?a.imageArray.length-1:a.activeImage-1);return false}),b("#nextLink,#nextLinkText").show().click(function(){g(a.activeImage==a.imageArray.length-1?0:a.activeImage+1);return false})):(a.activeImage!=0&&b("#prevLink,#prevLinkText").show().click(function(){g(a.activeImage-1);return false}),a.activeImage!=a.imageArray.length-1&&b("#nextLink,#nextLinkText").show().click(function(){g(a.activeImage+
1);return false})),b(document).bind("keydown",{opts:a},s))}function s(b){var c=b.data.opts,b=b.keyCode,d=String.fromCharCode(b).toLowerCase();if(d=="x"||d=="o"||d=="c"||b==27)m();else if(d=="p"||b==37)c.loopImages?(l(),g(c.activeImage==0?c.imageArray.length-1:c.activeImage-1)):c.activeImage!=0&&(l(),g(c.activeImage-1));else if(d=="n"||b==39)a.loopImages?(l(),g(c.activeImage==c.imageArray.length-1?0:c.activeImage+1)):c.activeImage!=c.imageArray.length-1&&(l(),g(c.activeImage+1))}function l(){b(document).unbind("keydown")}
var a=b.extend({},b.fn.lightbox.defaults,h);b(window).resize(n);return b(this).live(a.triggerEvent,function(){d();o(this);return false})};b.fn.lightbox.parseJsonData=function(h){var d=[];b.each(h,function(){d.push([this.url,this.title])});return d};b.fn.lightbox.defaults={triggerEvent:"click",allSet:false,fileLoadingImage:"images/loading.gif",fileBottomNavCloseImage:"images/closelabel.gif",overlayOpacity:0.6,borderSize:10,imageArray:[],activeImage:null,inprogress:false,resizeSpeed:350,widthCurrent:250,
heightCurrent:250,scaleImages:false,xScale:1,yScale:1,displayTitle:true,navbarOnTop:false,displayDownloadLink:false,slideNavBar:false,navBarSlideSpeed:350,displayHelp:false,strings:{help:" ← / P - previous image    → / N - next image    ESC / X - close image gallery",prevLinkTitle:"previous image",nextLinkTitle:"next image",prevLinkText:"&laquo; Previous",nextLinkText:"Next &raquo;",closeTitle:"close image gallery",image:"Image ",of:" of ",download:"Download"},fitToScreen:false,disableNavbarLinks:false,
loopImages:false,imageClickClose:true,jsonData:null,jsonDataParser:null}})(jQuery);jQuery(function(b){var h=[];b("a[class=media]").each(function(){var d=b(this).find("img");if(d.length){var d=d[0],k=d.src,k=k.replace(/\?w=\d+/,"");h.push([k,d.title||""]);this.href=k}else return false}).lightbox({fileLoadingImage:"lib/plugins/lightbox/images/loading.gif",fileBottomNavCloseImage:"lib/plugins/lightbox/images/closelabel.gif",fitToScreen:true,jsonData:h,jsonDataParser:function(b){return b}})});
